#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Dec 21, 2018 07:12:42 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x800+576+52
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 800 800
    wm minsize $top 800 800
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Module drag and drop"
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command select_files \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Open Files} 
    vTcl:DefineAlias "$top.but40" "Button1" vTcl:WidgetProc "$top" 1
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 765 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra41" "Frame1" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra41
    message $site_3_0.mes42 \
        -anchor nw -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Naming Scheme:

_ is used as separator.

groupname_type_nr-in-group

groupname:
Can be anything as long as it does not contain seporators.

type:
Type of component (see list below for possibilities)

nr:
Nr. of component in group.

options:
Include 'left' or 'right' in the group name if you potentially want your group to be mirrored.
Include 'nogroup' no group will be assigned. This MUST be done for ship wide shields otherwise the shield will shield the components in the group only.

Examples:
left-top-bat-1_lturret_2
let-nogroup_lshield_1

Injection and Mirroring:
Mirroring can be turned off and on for each file or individually. Mirroring will be done over the left/right side.

Injection can be turned off and on for each file or individually. When injecting is on user will be promted what file to inject into.
All new connections will be injected below the last connection in the selected file.} \
        -width 392 
    vTcl:DefineAlias "$site_3_0.mes42" "Message1" vTcl:WidgetProc "$top" 1
    place $site_3_0.mes42 \
        -in $site_3_0 -x 1 -y 7 -width 392 -relwidth 0 -height 750 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Select Files to be processed} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "$top" 1
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 245 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra44" "Frame3" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra44
    listbox $site_3_0.lis45 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 245 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 345 -listvariable file_list 
    .top39.fra44.lis45 configure -font TkFixedFont
    .top39.fra44.lis45 insert end text
    vTcl:DefineAlias "$site_3_0.lis45" "file_list_box" vTcl:WidgetProc "$top" 1
    bind $site_3_0.lis45 <<ToggleSelection>> {
        lambda e: xxx(e)
    }
    place $site_3_0.lis45 \
        -in $site_3_0 -x 0 -y 0 -width 345 -relwidth 0 -height 245 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 145 \
        -width 205 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra46
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command mirror_on \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Mirror On} 
    vTcl:DefineAlias "$site_3_0.but48" "mirror_on" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {On selected files} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label3" vTcl:WidgetProc "$top" 1
    button $site_3_0.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command mirror_off \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Mirror Off} 
    vTcl:DefineAlias "$site_3_0.but50" "mirror_off" vTcl:WidgetProc "$top" 1
    button $site_3_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command inject_on \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Inject On} 
    vTcl:DefineAlias "$site_3_0.but56" "Button5" vTcl:WidgetProc "$top" 1
    button $site_3_0.but57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command inject_off \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Inject Off} 
    vTcl:DefineAlias "$site_3_0.but57" "Button6" vTcl:WidgetProc "$top" 1
    place $site_3_0.but48 \
        -in $site_3_0 -x 20 -y 40 -width 76 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 10 -y 10 -width 182 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 110 -y 40 -width 78 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 20 -y 90 -width 76 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 110 -y 90 -width 76 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra52 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 145 \
        -width 205 
    vTcl:DefineAlias "$top.fra52" "Frame4" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {On all files} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3_2" vTcl:WidgetProc "$top" 1
    button $site_3_0.but54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command all_mirror_off \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Mirror Off} 
    vTcl:DefineAlias "$site_3_0.but54" "Button4" vTcl:WidgetProc "$top" 1
    button $site_3_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command all_mirror_on \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Mirror On} 
    vTcl:DefineAlias "$site_3_0.but55" "Button4_3" vTcl:WidgetProc "$top" 1
    button $site_3_0.but58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command all_inject_on \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Inject On} 
    vTcl:DefineAlias "$site_3_0.but58" "Button7" vTcl:WidgetProc "$top" 1
    button $site_3_0.but59 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command all_inject_off \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Inject Off} 
    vTcl:DefineAlias "$site_3_0.but59" "Button7_4" vTcl:WidgetProc "$top" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 10 -y 10 -width 182 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 110 -y 40 -width 76 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 20 -y 40 -width 76 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 20 -y 90 -width 76 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 110 -y 90 -width 76 -height 33 -anchor nw \
        -bordermode ignore 
    button $top.but60 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command start_processing \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Start 
    vTcl:DefineAlias "$top.but60" "Button4" vTcl:WidgetProc "$top" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but40 \
        -in $top -x 30 -y 40 -anchor nw -bordermode ignore 
    place $top.fra41 \
        -in $top -x 380 -y 20 -width 405 -relwidth 0 -height 765 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 30 -y 10 -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 30 -y 80 -width 345 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 30 -y 330 -width 205 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 30 -y 480 -width 205 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 30 -y 640 -width 206 -relwidth 0 -height 143 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

